export const FETCH_SONGS = 'songs/FETCH_ALL'
export const FETCH_SONGS_SUCCESS = 'songs/FETCH_ALL_SUCCESS'

export const FETCH_PLAYLISTS = 'playlist/FETCH_PLAYLISTS'
export const FETCH_PLAYLISTS_SUCCESS = 'playlist/FETCH_PLAYLISTS_SUCCESS'
export const OPEN_PLAYLIST_MODAL = 'playlist/OPEN_PLAYLIST_MODAL'
export const CLOSE_PLAYLIST_MODAL = 'playlist/CLOSE_PLAYLIST_MODAL'

export const ADD_SONG_TO_PLAYLIST = 'playlist/ADD_SONG_TO_PLAYLIST'
export const REMOVE_SONG_FROM_PLAYLIST = 'playlist/REMOVE_SONG_FROM_PLAYLIST'
export const ADD_PLAYLIST_TITLE = 'playlist/ADD_PLAYLIST_TITLE'
export const CREATE_PLAYLIST = 'playlist/CREATE_PLAYLIST'

export const SHOW_NAME_REQUIRED_ALERT = 'playlist/SHOW_NAME_REQUIRED_ALERT'
export const SHOW_NAME_REQUIRED_ALERT_CLOSE = 'playlist/SHOW_NAME_REQUIRED_ALERT_CLOSE'
export const OPEN_PLAY_LIST_MODAL_TO_ADD_SONGS = 'playlist/OPEN_PLAY_LIST_MODAL_TO_ADD_SONGS'
export const CLOSE_PLAY_LIST_MODAL = 'playlist/CLOSE_PLAY_LIST_MODAL'
export const ADD_NEW_SONG_TO_PLAYLIST = 'playlist/ADD_NEW_SONG_TO_PLAYLIST'
export const ADD_SONG_TO_PLAYLIST_SUCCESS = 'playlist/ADD_SONG_TO_PLAYLIST_SUCCESS'